openapi: 3.0.3
info:
    title: readworld app example
    description: readworld app example
    version: 0.0.1
servers:
    - url: http://localhost:8080
paths:
    /api/user/current:
        get:
            tags:
                - user
            summary: getCurrentUser user
            operationId: user#getCurrentUser
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Placeat perspiciatis molestiae.
                                    email: Aut aliquid corrupti quae.
                                    image: Ut ipsum.
                                    token: Voluptates consequatur ab sint sit repellendus.
                                    username: Officia ut necessitatibus aut et maiores.
    /api/user/login:
        post:
            tags:
                - user
            summary: login user
            operationId: user#login
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginRequestBody'
                        example:
                            email: jaylen.kuhic@ledner.net
                            password: yj4
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Placeat perspiciatis molestiae.
                                    email: Aut aliquid corrupti quae.
                                    image: Ut ipsum.
                                    token: Voluptates consequatur ab sint sit repellendus.
                                    username: Officia ut necessitatibus aut et maiores.
                "400":
                    description: 'PasswordIsIncorrect: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/user/register:
        post:
            tags:
                - user
            summary: register user
            operationId: user#register
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RegisterRequestBody'
                        example:
                            email: preston.powlowski@mosciskiparisian.com
                            password: hhp
                            username: Lonx
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Placeat perspiciatis molestiae.
                                    email: Aut aliquid corrupti quae.
                                    image: Ut ipsum.
                                    token: Voluptates consequatur ab sint sit repellendus.
                                    username: Officia ut necessitatibus aut et maiores.
                "400":
                    description: 'EmailAlreadyUsed: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/user/update:
        post:
            tags:
                - user
            summary: updateUser user
            operationId: user#updateUser
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateUserRequestBody'
                        example:
                            bio: 6ge
                            email: bud_olson@rempelstracke.info
                            image: http://ru
                            password: eax
                            username: 6fd
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Placeat perspiciatis molestiae.
                                    email: Aut aliquid corrupti quae.
                                    image: Ut ipsum.
                                    token: Voluptates consequatur ab sint sit repellendus.
                                    username: Officia ut necessitatibus aut et maiores.
components:
    schemas:
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        LoginRequestBody:
            type: object
            properties:
                email:
                    type: string
                    example: erna_mcdermott@starkschultz.biz
                    format: email
                password:
                    type: string
                    example: 0ix
                    minLength: 6
                    maxLength: 128
            example:
                email: jennyfer@west.net
                password: rye
            required:
                - email
                - password
        LoginResponseBody:
            type: object
            properties:
                user:
                    $ref: '#/components/schemas/User'
            example:
                user:
                    bio: Placeat perspiciatis molestiae.
                    email: Aut aliquid corrupti quae.
                    image: Ut ipsum.
                    token: Voluptates consequatur ab sint sit repellendus.
                    username: Officia ut necessitatibus aut et maiores.
            required:
                - user
        RegisterRequestBody:
            type: object
            properties:
                email:
                    type: string
                    example: napoleon.jenkins@hauck.biz
                    format: email
                password:
                    type: string
                    example: o24
                    minLength: 6
                    maxLength: 128
                username:
                    type: string
                    example: JH7UEk
                    pattern: ^[a-zA-Z0-9_]{3,32}$
            example:
                email: ryley@hyatt.net
                password: u0l
                username: 4TT
            required:
                - username
                - email
                - password
        UpdateUserRequestBody:
            type: object
            properties:
                bio:
                    type: string
                    example: wvq
                    maxLength: 4096
                email:
                    type: string
                    example: elva@huelshettinger.name
                    format: email
                image:
                    type: string
                    example: http://7l
                    pattern: ^http://.+$
                password:
                    type: string
                    example: 8gh
                    minLength: 6
                    maxLength: 128
                username:
                    type: string
                    example: LP5
                    pattern: ^[a-zA-Z0-9_]{3,32}$
            example:
                bio: 5ws
                email: therese@stehr.com
                image: http://zu
                password: c57
                username: 35i4GwR
        User:
            type: object
            properties:
                bio:
                    type: string
                    example: Et fugiat laudantium et pariatur inventore.
                email:
                    type: string
                    example: Repellendus nihil amet consectetur pariatur reprehenderit.
                image:
                    type: string
                    example: Alias eius facere corrupti est.
                token:
                    type: string
                    example: Ad aspernatur aut enim nihil.
                username:
                    type: string
                    example: Laborum expedita ipsa iste fugit.
            example:
                bio: Aliquid voluptatem adipisci magnam placeat.
                email: Qui est blanditiis reprehenderit.
                image: Itaque maiores atque ea.
                token: Quis officiis.
                username: Quia illo porro itaque odit ex velit.
            required:
                - email
                - token
                - username
                - bio
                - image
tags:
    - name: user
      description: user
