openapi: 3.0.3
info:
    title: readworld app example
    description: readworld app example
    version: 0.0.1
servers:
    - url: http://localhost:8080
paths:
    /api/profile/follow_user:
        post:
            tags:
                - profile
            summary: followUser profile
            operationId: profile#followUser
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/FollowUserRequestBody'
                        example:
                            username: zn5
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FollowUserResponseBody'
                            example:
                                profile:
                                    bio: Beatae et.
                                    following: true
                                    image: Amet pariatur sit omnis aut aliquid corrupti.
                                    username: Enim ab commodi odio voluptate.
                "400":
                    description: 'UserAlreadyFollowing: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/profile/unfollow_user:
        post:
            tags:
                - profile
            summary: unfollowUser profile
            operationId: profile#unfollowUser
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/FollowUserRequestBody'
                        example:
                            username: C2PiK
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FollowUserResponseBody'
                            example:
                                profile:
                                    bio: Beatae et.
                                    following: true
                                    image: Amet pariatur sit omnis aut aliquid corrupti.
                                    username: Enim ab commodi odio voluptate.
                "400":
                    description: 'UserNotFollowing: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/user/current:
        get:
            tags:
                - user
            summary: getCurrent user
            operationId: user#getCurrent
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Autem repellendus tenetur maiores est et.
                                    email: Omnis ut dolorem aperiam ducimus.
                                    image: Esse eligendi voluptas placeat nisi.
                                    token: Est vel autem sequi est.
                                    username: Et corrupti voluptatum enim aut.
    /api/user/login:
        post:
            tags:
                - user
            summary: login user
            operationId: user#login
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginRequestBody'
                        example:
                            email: ophelia@stehr.biz
                            password: sm4
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Autem repellendus tenetur maiores est et.
                                    email: Omnis ut dolorem aperiam ducimus.
                                    image: Esse eligendi voluptas placeat nisi.
                                    token: Est vel autem sequi est.
                                    username: Et corrupti voluptatum enim aut.
                "400":
                    description: 'PasswordIsIncorrect: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/user/register:
        post:
            tags:
                - user
            summary: register user
            operationId: user#register
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RegisterRequestBody'
                        example:
                            email: raymond@roobschimmel.biz
                            password: uip
                            username: q4I
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Autem repellendus tenetur maiores est et.
                                    email: Omnis ut dolorem aperiam ducimus.
                                    image: Esse eligendi voluptas placeat nisi.
                                    token: Est vel autem sequi est.
                                    username: Et corrupti voluptatum enim aut.
                "400":
                    description: 'EmailAlreadyUsed: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/user/update:
        post:
            tags:
                - user
            summary: update user
            operationId: user#update
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateRequestBody'
                        example:
                            bio: w3n
                            email: eleonore@reichel.biz
                            image: https://o1
                            password: 1po
                            username: 05i1T
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Autem repellendus tenetur maiores est et.
                                    email: Omnis ut dolorem aperiam ducimus.
                                    image: Esse eligendi voluptas placeat nisi.
                                    token: Est vel autem sequi est.
                                    username: Et corrupti voluptatum enim aut.
components:
    schemas:
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        FollowUserRequestBody:
            type: object
            properties:
                username:
                    type: string
                    example: aTgu
                    pattern: ^[a-zA-Z0-9_]{3,32}$
            example:
                username: rePfCr
            required:
                - username
        FollowUserResponseBody:
            type: object
            properties:
                profile:
                    $ref: '#/components/schemas/Profile'
            example:
                profile:
                    bio: Beatae et.
                    following: true
                    image: Amet pariatur sit omnis aut aliquid corrupti.
                    username: Enim ab commodi odio voluptate.
            required:
                - profile
        LoginRequestBody:
            type: object
            properties:
                email:
                    type: string
                    example: eliezer.muller@hegmannhilpert.biz
                    format: email
                password:
                    type: string
                    example: wvd
                    minLength: 6
                    maxLength: 128
            example:
                email: donavon_bernier@hermanokon.org
                password: 34t
            required:
                - email
                - password
        LoginResponseBody:
            type: object
            properties:
                user:
                    $ref: '#/components/schemas/User'
            example:
                user:
                    bio: Autem repellendus tenetur maiores est et.
                    email: Omnis ut dolorem aperiam ducimus.
                    image: Esse eligendi voluptas placeat nisi.
                    token: Est vel autem sequi est.
                    username: Et corrupti voluptatum enim aut.
            required:
                - user
        Profile:
            type: object
            properties:
                bio:
                    type: string
                    example: Et sint ut soluta libero.
                following:
                    type: boolean
                    example: false
                image:
                    type: string
                    example: Aut debitis quos ut odio et accusamus.
                username:
                    type: string
                    example: Alias possimus voluptates rerum voluptatem nam.
            example:
                bio: Rerum non non eum eum.
                following: true
                image: Dignissimos impedit culpa nobis temporibus voluptas.
                username: Delectus alias laboriosam et.
            required:
                - username
                - bio
                - image
                - following
        RegisterRequestBody:
            type: object
            properties:
                email:
                    type: string
                    example: franz_muller@senger.name
                    format: email
                password:
                    type: string
                    example: n7b
                    minLength: 6
                    maxLength: 128
                username:
                    type: string
                    example: 2WF
                    pattern: ^[a-zA-Z0-9_]{3,32}$
            example:
                email: zoey_corwin@deckow.net
                password: ssu
                username: von
            required:
                - username
                - email
                - password
        UpdateRequestBody:
            type: object
            properties:
                bio:
                    type: string
                    example: gqb
                    maxLength: 4096
                email:
                    type: string
                    example: vivienne@schneider.net
                    format: email
                image:
                    type: string
                    example: http://lt
                    pattern: ^https?://.+$
                password:
                    type: string
                    example: a0y
                    minLength: 6
                    maxLength: 128
                username:
                    type: string
                    example: 9OUsR
                    pattern: ^[a-zA-Z0-9_]{3,32}$
            example:
                bio: u5l
                email: cynthia@stoltenberglockman.net
                image: https://73
                password: 75a
                username: NIt
        User:
            type: object
            properties:
                bio:
                    type: string
                    example: Occaecati quas quis excepturi.
                email:
                    type: string
                    example: Omnis magnam velit.
                image:
                    type: string
                    example: Provident iste eum.
                token:
                    type: string
                    example: Soluta porro quia odit excepturi possimus molestiae.
                username:
                    type: string
                    example: Libero veniam voluptatem.
            example:
                bio: Quo tenetur.
                email: Ullam ea provident voluptates laborum hic laborum.
                image: Quos sunt aut maiores numquam aut.
                token: Incidunt iure optio omnis.
                username: Autem voluptates harum et neque minus eveniet.
            required:
                - email
                - token
                - username
                - bio
                - image
tags:
    - name: profile
      description: profile
    - name: user
      description: user
