openapi: 3.0.3
info:
    title: readworld app example
    description: readworld app example
    version: 0.0.1
servers:
    - url: http://localhost:8080
paths:
    /api/user/current:
        get:
            tags:
                - user
            summary: getCurrent user
            operationId: user#getCurrent
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Necessitatibus aut et maiores officiis placeat.
                                    email: Aliquid corrupti quae reprehenderit voluptates consequatur.
                                    image: Molestiae incidunt.
                                    token: Sint sit.
                                    username: Sed officia.
    /api/user/login:
        post:
            tags:
                - user
            summary: login user
            operationId: user#login
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginRequestBody'
                        example:
                            email: jaylen@lueilwitz.info
                            password: j4i
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Necessitatibus aut et maiores officiis placeat.
                                    email: Aliquid corrupti quae reprehenderit voluptates consequatur.
                                    image: Molestiae incidunt.
                                    token: Sint sit.
                                    username: Sed officia.
                "400":
                    description: 'PasswordIsIncorrect: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/user/register:
        post:
            tags:
                - user
            summary: register user
            operationId: user#register
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RegisterRequestBody'
                        example:
                            email: shana@rolfsonpowlowski.biz
                            password: q8f
                            username: ObL
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Necessitatibus aut et maiores officiis placeat.
                                    email: Aliquid corrupti quae reprehenderit voluptates consequatur.
                                    image: Molestiae incidunt.
                                    token: Sint sit.
                                    username: Sed officia.
                "400":
                    description: 'EmailAlreadyUsed: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/user/update:
        post:
            tags:
                - user
            summary: update user
            operationId: user#update
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateRequestBody'
                        example:
                            bio: lru
                            email: aniyah_king@bosco.biz
                            image: http://ea
                            password: ty7
                            username: DCt
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Necessitatibus aut et maiores officiis placeat.
                                    email: Aliquid corrupti quae reprehenderit voluptates consequatur.
                                    image: Molestiae incidunt.
                                    token: Sint sit.
                                    username: Sed officia.
components:
    schemas:
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        LoginRequestBody:
            type: object
            properties:
                email:
                    type: string
                    example: kacie_keebler@lebsack.org
                    format: email
                password:
                    type: string
                    example: 2he
                    minLength: 6
                    maxLength: 128
            example:
                email: seamus@kertzmannpfannerstill.com
                password: rah
            required:
                - email
                - password
        LoginResponseBody:
            type: object
            properties:
                user:
                    $ref: '#/components/schemas/User'
            example:
                user:
                    bio: Necessitatibus aut et maiores officiis placeat.
                    email: Aliquid corrupti quae reprehenderit voluptates consequatur.
                    image: Molestiae incidunt.
                    token: Sint sit.
                    username: Sed officia.
            required:
                - user
        RegisterRequestBody:
            type: object
            properties:
                email:
                    type: string
                    example: vaughn@bode.com
                    format: email
                password:
                    type: string
                    example: "515"
                    minLength: 6
                    maxLength: 128
                username:
                    type: string
                    example: QW_n
                    pattern: ^[a-zA-Z0-9_]{3,32}$
            example:
                email: alessia@kohler.com
                password: 2a7
                username: 2hIk
            required:
                - username
                - email
                - password
        UpdateRequestBody:
            type: object
            properties:
                bio:
                    type: string
                    example: vql
                    maxLength: 4096
                email:
                    type: string
                    example: elva_reinger@waelchi.name
                    format: email
                image:
                    type: string
                    example: http://li
                    pattern: ^https?://.+$
                password:
                    type: string
                    example: 8gh
                    minLength: 6
                    maxLength: 128
                username:
                    type: string
                    example: xvyo7ulP
                    pattern: ^[a-zA-Z0-9_]{3,32}$
            example:
                bio: 57n
                email: alayna_o'keefe@kling.info
                image: http://rf
                password: ioy
                username: 5iI
        User:
            type: object
            properties:
                bio:
                    type: string
                    example: Ipsam laborum expedita.
                email:
                    type: string
                    example: Nihil amet.
                image:
                    type: string
                    example: Iste fugit eos et fugiat laudantium.
                token:
                    type: string
                    example: Pariatur reprehenderit rerum ad.
                username:
                    type: string
                    example: Aut enim.
            example:
                bio: Quis officiis.
                email: Pariatur inventore earum.
                image: Quia illo porro itaque odit ex velit.
                token: Eius facere corrupti est maxime.
                username: Est blanditiis reprehenderit.
            required:
                - email
                - token
                - username
                - bio
                - image
tags:
    - name: user
      description: user
