swagger: "2.0"
info:
    title: readworld app example
    description: readworld app example
    version: 0.0.1
host: localhost:8080
basePath: api
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/user:
        get:
            tags:
                - user
            summary: getCurrentUser user
            operationId: user#getCurrentUser
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UserGetCurrentUserResponseBody'
                        required:
                            - user
            schemes:
                - http
    /api/users:
        post:
            tags:
                - user
            summary: register user
            operationId: user#register
            parameters:
                - name: RegisterRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UserRegisterRequestBody'
                    required:
                        - username
                        - email
                        - password
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UserRegisterResponseBody'
                        required:
                            - user
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/UserRegisterEmailAlreadyUsedResponseBody'
            schemes:
                - http
    /api/users/login:
        post:
            tags:
                - user
            summary: login user
            operationId: user#login
            parameters:
                - name: LoginRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UserLoginRequestBody'
                    required:
                        - email
                        - password
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UserLoginResponseBody'
                        required:
                            - user
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/UserLoginPasswordIsIncorrectResponseBody'
            schemes:
                - http
definitions:
    User:
        title: User
        type: object
        properties:
            bio:
                type: string
                example: Non nihil.
            email:
                type: string
                example: Sit quis.
            image:
                type: string
                example: A harum et.
            token:
                type: string
                example: Reprehenderit fugit eum voluptas voluptas et laboriosam.
            username:
                type: string
                example: Autem sed ipsa est.
        example:
            bio: Sapiente dolorum velit accusamus laborum.
            email: Qui modi temporibus dolorem.
            image: Velit omnis ut dolorem aperiam ducimus.
            token: Dolores esse et non voluptas aut.
            username: Sed ut et enim sunt sint.
        required:
            - email
            - token
            - username
            - bio
            - image
    UserGetCurrentUserResponseBody:
        title: UserGetCurrentUserResponseBody
        type: object
        properties:
            user:
                $ref: '#/definitions/User'
        example:
            user:
                bio: Quos ea minima labore.
                email: Eveniet repudiandae velit et.
                image: Corporis sit facilis ut ut sunt.
                token: Eos dolorum incidunt quia corporis doloribus provident.
                username: Sit aliquam rerum voluptatem rerum.
        required:
            - user
    UserLoginEmailNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: login_EmailNotFound_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserLoginPasswordIsIncorrectResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: login_PasswordIsIncorrect_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserLoginRequestBody:
        title: UserLoginRequestBody
        type: object
        properties:
            email:
                type: string
                example: aniyah_king@bosco.biz
                format: email
            password:
                type: string
                example: ty7
                minLength: 6
                maxLength: 128
        example:
            email: vern_jacobson@thiel.org
            password: f2a
        required:
            - email
            - password
    UserLoginResponseBody:
        title: UserLoginResponseBody
        type: object
        properties:
            user:
                $ref: '#/definitions/User'
        example:
            user:
                bio: Quos ea minima labore.
                email: Eveniet repudiandae velit et.
                image: Corporis sit facilis ut ut sunt.
                token: Eos dolorum incidunt quia corporis doloribus provident.
                username: Sit aliquam rerum voluptatem rerum.
        required:
            - user
    UserRegisterEmailAlreadyUsedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: register_EmailAlreadyUsed_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserRegisterRequestBody:
        title: UserRegisterRequestBody
        type: object
        properties:
            email:
                type: string
                example: gaetano_lindgren@steuber.info
                format: email
            password:
                type: string
                example: 9wx
                minLength: 6
                maxLength: 128
            username:
                type: string
                example: OmWfz
                pattern: ^[a-zA-Z0-9_]{3,32}$
        example:
            email: verlie@kuhnwehner.biz
            password: 1ux
            username: 0jB
        required:
            - username
            - email
            - password
    UserRegisterResponseBody:
        title: UserRegisterResponseBody
        type: object
        properties:
            user:
                $ref: '#/definitions/User'
        example:
            user:
                bio: Quos ea minima labore.
                email: Eveniet repudiandae velit et.
                image: Corporis sit facilis ut ut sunt.
                token: Eos dolorum incidunt quia corporis doloribus provident.
                username: Sit aliquam rerum voluptatem rerum.
        required:
            - user
    UserRegisterUsernameAlreadyUsedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: register_UsernameAlreadyUsed_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
