openapi: 3.0.3
info:
    title: readworld app example
    description: readworld app example
    version: 0.0.1
servers:
    - url: http://localhost:8080
paths:
    /api/users/login:
        post:
            tags:
                - user
            summary: login user
            operationId: user#login
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginRequestBody'
                        example:
                            email: hermann.swift@bernhard.com
                            password: Pariatur saepe placeat a perferendis occaecati assumenda.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Beatae et.
                                    email: savanna@hauck.name
                                    image: Amet pariatur sit omnis aut aliquid corrupti.
                                    token: Nisi nihil aut labore.
                                    username: Enim ab commodi odio voluptate.
components:
    schemas:
        LoginRequestBody:
            type: object
            properties:
                email:
                    type: string
                    example: delfina_hartmann@terry.net
                    format: email
                password:
                    type: string
                    example: Fuga adipisci nostrum quae aut.
            example:
                email: emily_cole@dietrich.net
                password: Officiis qui quia voluptas laboriosam.
            required:
                - email
                - password
        LoginResponseBody:
            type: object
            properties:
                user:
                    $ref: '#/components/schemas/UserType'
            example:
                user:
                    bio: Beatae et.
                    email: savanna@hauck.name
                    image: Amet pariatur sit omnis aut aliquid corrupti.
                    token: Nisi nihil aut labore.
                    username: Enim ab commodi odio voluptate.
            required:
                - user
        UserType:
            type: object
            properties:
                bio:
                    type: string
                    example: Eveniet consequuntur non voluptas quo debitis quia.
                email:
                    type: string
                    example: cade.trantow@hamill.biz
                    format: email
                image:
                    type: string
                    example: Pariatur et minima minima dolorem aut.
                token:
                    type: string
                    example: Cupiditate qui consequuntur error laboriosam.
                username:
                    type: string
                    example: Eveniet consequatur non laborum nesciunt exercitationem voluptas.
            example:
                bio: Neque distinctio eligendi perspiciatis voluptatem dolore.
                email: nathanial_jacobson@ebert.info
                image: Quas in voluptatibus ut alias.
                token: Et qui earum qui exercitationem dicta.
                username: Accusamus facilis et doloremque.
            required:
                - email
                - token
                - username
                - bio
                - image
tags:
    - name: user
      description: user
