openapi: 3.0.3
info:
    title: readworld app example
    description: readworld app example
    version: 0.0.1
servers:
    - url: http://localhost:8080
paths:
    /api/user:
        get:
            tags:
                - user
            summary: getCurrentUser user
            operationId: user#getCurrentUser
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Doloribus provident.
                                    email: Perferendis occaecati assumenda.
                                    image: Sit aliquam rerum voluptatem rerum.
                                    token: Expedita non vel velit explicabo eveniet repudiandae.
                                    username: Et quam eos dolorum incidunt quia.
    /api/users:
        post:
            tags:
                - user
            summary: register user
            operationId: user#register
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RegisterRequestBody'
                        example:
                            email: alverta@marvin.com
                            password: g4r
                            username: i{3, 32}
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Doloribus provident.
                                    email: Perferendis occaecati assumenda.
                                    image: Sit aliquam rerum voluptatem rerum.
                                    token: Expedita non vel velit explicabo eveniet repudiandae.
                                    username: Et quam eos dolorum incidunt quia.
                "400":
                    description: 'EmailAlreadyUsed: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/users/login:
        post:
            tags:
                - user
            summary: login user
            operationId: user#login
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginRequestBody'
                        example:
                            email: hermann.swift@bernhard.com
                            password: 24h
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Doloribus provident.
                                    email: Perferendis occaecati assumenda.
                                    image: Sit aliquam rerum voluptatem rerum.
                                    token: Expedita non vel velit explicabo eveniet repudiandae.
                                    username: Et quam eos dolorum incidunt quia.
                "400":
                    description: 'PasswordIsIncorrect: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        LoginRequestBody:
            type: object
            properties:
                email:
                    type: string
                    example: ceasar@schuppe.org
                    format: email
                password:
                    type: string
                    example: kb8
                    minLength: 6
                    maxLength: 128
            example:
                email: nia.muller@mayert.biz
                password: qza
            required:
                - email
                - password
        LoginResponseBody:
            type: object
            properties:
                user:
                    $ref: '#/components/schemas/User'
            example:
                user:
                    bio: Doloribus provident.
                    email: Perferendis occaecati assumenda.
                    image: Sit aliquam rerum voluptatem rerum.
                    token: Expedita non vel velit explicabo eveniet repudiandae.
                    username: Et quam eos dolorum incidunt quia.
            required:
                - user
        RegisterRequestBody:
            type: object
            properties:
                email:
                    type: string
                    example: eugene.kovacek@koeppkris.biz
                    format: email
                password:
                    type: string
                    example: oz2
                    minLength: 6
                    maxLength: 128
                username:
                    type: string
                    example: e{3, 32}
                    pattern: ^[a-z0-9_]{3, 32}$
            example:
                email: lemuel_jast@kerluke.net
                password: 9ae
                username: g{3, 32}
            required:
                - username
                - email
                - password
        User:
            type: object
            properties:
                bio:
                    type: string
                    example: Eveniet consequuntur non voluptas quo debitis quia.
                email:
                    type: string
                    example: Illum repellendus.
                image:
                    type: string
                    example: Pariatur et minima minima dolorem aut.
                token:
                    type: string
                    example: Qui consequuntur error laboriosam numquam eveniet.
                username:
                    type: string
                    example: Non laborum nesciunt exercitationem voluptas.
            example:
                bio: Quam aut aliquam consequatur vel nostrum qui.
                email: Debitis vero explicabo quod occaecati veritatis.
                image: Vel voluptatem deserunt.
                token: Possimus deleniti quas ad aliquam.
                username: Officiis vero voluptatum.
            required:
                - email
                - token
                - username
                - bio
                - image
tags:
    - name: user
      description: user
