swagger: "2.0"
info:
    title: readworld app example
    description: readworld app example
    version: 0.0.1
host: localhost:8080
basePath: api
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/users:
        post:
            tags:
                - user
            summary: register user
            operationId: user#register
            parameters:
                - name: RegisterRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UserRegisterRequestBody'
                    required:
                        - username
                        - email
                        - password
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UserRegisterResponseBody'
                        required:
                            - user
            schemes:
                - http
    /api/users/login:
        post:
            tags:
                - user
            summary: login user
            operationId: user#login
            parameters:
                - name: LoginRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UserLoginRequestBody'
                    required:
                        - email
                        - password
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UserLoginResponseBody'
                        required:
                            - user
            schemes:
                - http
definitions:
    UserLoginRequestBody:
        title: UserLoginRequestBody
        type: object
        properties:
            email:
                type: string
                example: saul_shanahan@strosinrutherford.biz
                format: email
            password:
                type: string
                example: Eveniet consequatur non laborum nesciunt exercitationem voluptas.
        example:
            email: isabell@schusterfisher.net
            password: Consectetur quos.
        required:
            - email
            - password
    UserLoginResponseBody:
        title: UserLoginResponseBody
        type: object
        properties:
            user:
                $ref: '#/definitions/UserType'
        example:
            user:
                bio: Et optio qui.
                email: sedrick@terryauer.net
                image: Temporibus dolorem illo dolores esse et.
                token: Laboriosam quae autem sed ipsa est ratione.
                username: Nihil pariatur a.
        required:
            - user
    UserRegisterRequestBody:
        title: UserRegisterRequestBody
        type: object
        properties:
            email:
                type: string
                example: kariane_yost@fritschbogan.name
                format: email
            password:
                type: string
                example: Animi tempora facere officiis totam.
            username:
                type: string
                example: Quam earum quis quae quos et illo.
        example:
            email: dallin.auer@stamm.name
            password: Accusamus et ut.
            username: Dolor nesciunt.
        required:
            - username
            - email
            - password
    UserRegisterResponseBody:
        title: UserRegisterResponseBody
        type: object
        properties:
            user:
                $ref: '#/definitions/UserType'
        example:
            user:
                bio: Et optio qui.
                email: sedrick@terryauer.net
                image: Temporibus dolorem illo dolores esse et.
                token: Laboriosam quae autem sed ipsa est ratione.
                username: Nihil pariatur a.
        required:
            - user
    UserType:
        title: UserType
        type: object
        properties:
            bio:
                type: string
                example: Ullam ut ex minus.
            email:
                type: string
                example: julien@rosenbaum.org
                format: email
            image:
                type: string
                example: Nam ipsam reiciendis sit autem.
            token:
                type: string
                example: Dolore praesentium dicta vel facilis reprehenderit.
            username:
                type: string
                example: Sed quasi.
        example:
            bio: Quis necessitatibus.
            email: moises@witting.info
            image: Aut sit est cum dolorum aut praesentium.
            token: Tempora consequuntur et.
            username: Perspiciatis provident.
        required:
            - email
            - token
            - username
            - bio
            - image
