swagger: "2.0"
info:
    title: readworld app example
    description: readworld app example
    version: 0.0.1
host: localhost:8080
basePath: api
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/user/current:
        get:
            tags:
                - user
            summary: getCurrentUser user
            operationId: user#getCurrentUser
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UserGetCurrentUserResponseBody'
                        required:
                            - user
            schemes:
                - http
    /api/user/login:
        post:
            tags:
                - user
            summary: login user
            operationId: user#login
            parameters:
                - name: LoginRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UserLoginRequestBody'
                    required:
                        - email
                        - password
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UserLoginResponseBody'
                        required:
                            - user
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/UserLoginPasswordIsIncorrectResponseBody'
            schemes:
                - http
    /api/user/register:
        post:
            tags:
                - user
            summary: register user
            operationId: user#register
            parameters:
                - name: RegisterRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UserRegisterRequestBody'
                    required:
                        - username
                        - email
                        - password
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UserRegisterResponseBody'
                        required:
                            - user
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/UserRegisterEmailAlreadyUsedResponseBody'
            schemes:
                - http
    /api/user/update:
        post:
            tags:
                - user
            summary: updateUser user
            operationId: user#updateUser
            parameters:
                - name: UpdateUserRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UserUpdateUserRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UserUpdateUserResponseBody'
                        required:
                            - user
            schemes:
                - http
definitions:
    User:
        title: User
        type: object
        properties:
            bio:
                type: string
                example: Dolore praesentium dicta vel facilis reprehenderit.
            email:
                type: string
                example: Ea laborum qui laudantium vero voluptas molestiae.
            image:
                type: string
                example: Sed quasi.
            token:
                type: string
                example: Quae voluptatem quasi dignissimos quod exercitationem.
            username:
                type: string
                example: Animi dolorem aut perferendis nesciunt aliquid.
        example:
            bio: Quia neque.
            email: Ullam ut ex minus.
            image: Quos omnis magni iste explicabo.
            token: Nam ipsam reiciendis sit autem.
            username: Nisi consequatur quo.
        required:
            - email
            - token
            - username
            - bio
            - image
    UserGetCurrentUserResponseBody:
        title: UserGetCurrentUserResponseBody
        type: object
        properties:
            user:
                $ref: '#/definitions/User'
        example:
            user:
                bio: Placeat perspiciatis molestiae.
                email: Aut aliquid corrupti quae.
                image: Ut ipsum.
                token: Voluptates consequatur ab sint sit repellendus.
                username: Officia ut necessitatibus aut et maiores.
        required:
            - user
    UserLoginEmailNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: login_EmailNotFound_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserLoginPasswordIsIncorrectResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: login_PasswordIsIncorrect_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserLoginRequestBody:
        title: UserLoginRequestBody
        type: object
        properties:
            email:
                type: string
                example: emilie.haag@collier.name
                format: email
            password:
                type: string
                example: 9r9
                minLength: 6
                maxLength: 128
        example:
            email: zena.nitzsche@jacobi.name
            password: "593"
        required:
            - email
            - password
    UserLoginResponseBody:
        title: UserLoginResponseBody
        type: object
        properties:
            user:
                $ref: '#/definitions/User'
        example:
            user:
                bio: Placeat perspiciatis molestiae.
                email: Aut aliquid corrupti quae.
                image: Ut ipsum.
                token: Voluptates consequatur ab sint sit repellendus.
                username: Officia ut necessitatibus aut et maiores.
        required:
            - user
    UserRegisterEmailAlreadyUsedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: register_EmailAlreadyUsed_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserRegisterRequestBody:
        title: UserRegisterRequestBody
        type: object
        properties:
            email:
                type: string
                example: manley@oconnelllangosh.biz
                format: email
            password:
                type: string
                example: "726"
                minLength: 6
                maxLength: 128
            username:
                type: string
                example: N7C
                pattern: ^[a-zA-Z0-9_]{3,32}$
        example:
            email: dwight_carter@hegmannosinski.net
            password: 2fn
            username: FTa
        required:
            - username
            - email
            - password
    UserRegisterResponseBody:
        title: UserRegisterResponseBody
        type: object
        properties:
            user:
                $ref: '#/definitions/User'
        example:
            user:
                bio: Placeat perspiciatis molestiae.
                email: Aut aliquid corrupti quae.
                image: Ut ipsum.
                token: Voluptates consequatur ab sint sit repellendus.
                username: Officia ut necessitatibus aut et maiores.
        required:
            - user
    UserRegisterUsernameAlreadyUsedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: register_UsernameAlreadyUsed_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserUpdateUserRequestBody:
        title: UserUpdateUserRequestBody
        type: object
        properties:
            bio:
                type: string
                example: krr
                maxLength: 4096
            email:
                type: string
                example: cedrick@skiles.name
                format: email
            image:
                type: string
                example: http://ym
                pattern: ^http://.+$
            password:
                type: string
                example: bds
                minLength: 6
                maxLength: 128
            username:
                type: string
                example: 0ZN
                pattern: ^[a-zA-Z0-9_]{3,32}$
        example:
            bio: f09
            email: tre.nicolas@deckowfisher.name
            image: http://a
            password: spo
            username: _P3z
    UserUpdateUserResponseBody:
        title: UserUpdateUserResponseBody
        type: object
        properties:
            user:
                $ref: '#/definitions/User'
        example:
            user:
                bio: Placeat perspiciatis molestiae.
                email: Aut aliquid corrupti quae.
                image: Ut ipsum.
                token: Voluptates consequatur ab sint sit repellendus.
                username: Officia ut necessitatibus aut et maiores.
        required:
            - user
