openapi: 3.0.3
info:
    title: readworld app example
    description: readworld app example
    version: 0.0.1
servers:
    - url: http://localhost:8080
paths:
    /api/profile/follow_user:
        post:
            tags:
                - profile
            summary: followUser profile
            operationId: profile#followUser
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/FollowUserRequestBody'
                        example:
                            username: zn5
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FollowUserResponseBody'
                            example:
                                profile:
                                    bio: Beatae et.
                                    following: true
                                    image: Amet pariatur sit omnis aut aliquid corrupti.
                                    username: Enim ab commodi odio voluptate.
                "400":
                    description: 'UserAlreadyFollowing: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/profile/unfollow_user:
        post:
            tags:
                - profile
            summary: unfollowUser profile
            operationId: profile#unfollowUser
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/FollowUserRequestBody'
                        example:
                            username: 6B82V
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FollowUserResponseBody'
                            example:
                                profile:
                                    bio: Beatae et.
                                    following: true
                                    image: Amet pariatur sit omnis aut aliquid corrupti.
                                    username: Enim ab commodi odio voluptate.
                "400":
                    description: 'UserNotFollowing: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/user/current:
        get:
            tags:
                - user
            summary: getCurrent user
            operationId: user#getCurrent
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Et corrupti voluptatum enim aut.
                                    email: Velit accusamus laborum.
                                    image: Autem repellendus tenetur maiores est et.
                                    token: Velit omnis ut dolorem aperiam ducimus.
                                    username: Est vel autem sequi est.
    /api/user/login:
        post:
            tags:
                - user
            summary: login user
            operationId: user#login
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginRequestBody'
                        example:
                            email: kari_blick@raynormccullough.name
                            password: bh9
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Et corrupti voluptatum enim aut.
                                    email: Velit accusamus laborum.
                                    image: Autem repellendus tenetur maiores est et.
                                    token: Velit omnis ut dolorem aperiam ducimus.
                                    username: Est vel autem sequi est.
                "400":
                    description: 'PasswordIsIncorrect: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/user/register:
        post:
            tags:
                - user
            summary: register user
            operationId: user#register
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RegisterRequestBody'
                        example:
                            email: madaline@hauckrenner.info
                            password: wxm
                            username: bnVB
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Et corrupti voluptatum enim aut.
                                    email: Velit accusamus laborum.
                                    image: Autem repellendus tenetur maiores est et.
                                    token: Velit omnis ut dolorem aperiam ducimus.
                                    username: Est vel autem sequi est.
                "400":
                    description: 'EmailAlreadyUsed: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/user/update:
        post:
            tags:
                - user
            summary: update user
            operationId: user#update
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateRequestBody'
                        example:
                            bio: 91p
                            email: felicity_cummerata@schoenwehner.com
                            image: http://rv
                            password: l1v
                            username: CD4
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Et corrupti voluptatum enim aut.
                                    email: Velit accusamus laborum.
                                    image: Autem repellendus tenetur maiores est et.
                                    token: Velit omnis ut dolorem aperiam ducimus.
                                    username: Est vel autem sequi est.
components:
    schemas:
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        FollowUserRequestBody:
            type: object
            properties:
                username:
                    type: string
                    example: 2hIk
                    pattern: ^[a-zA-Z0-9_]{3,32}$
            example:
                username: YxB
            required:
                - username
        FollowUserResponseBody:
            type: object
            properties:
                profile:
                    $ref: '#/components/schemas/Profile'
            example:
                profile:
                    bio: Beatae et.
                    following: true
                    image: Amet pariatur sit omnis aut aliquid corrupti.
                    username: Enim ab commodi odio voluptate.
            required:
                - profile
        LoginRequestBody:
            type: object
            properties:
                email:
                    type: string
                    example: louie@walsh.info
                    format: email
                password:
                    type: string
                    example: g0u
                    minLength: 6
                    maxLength: 128
            example:
                email: allie_nicolas@lednerhagenes.info
                password: kxm
            required:
                - email
                - password
        LoginResponseBody:
            type: object
            properties:
                user:
                    $ref: '#/components/schemas/User'
            example:
                user:
                    bio: Et corrupti voluptatum enim aut.
                    email: Velit accusamus laborum.
                    image: Autem repellendus tenetur maiores est et.
                    token: Velit omnis ut dolorem aperiam ducimus.
                    username: Est vel autem sequi est.
            required:
                - user
        Profile:
            type: object
            properties:
                bio:
                    type: string
                    example: Totam numquam quia consequuntur blanditiis velit.
                following:
                    type: boolean
                    example: false
                image:
                    type: string
                    example: Eum corrupti non neque.
                username:
                    type: string
                    example: Libero inventore.
            example:
                bio: Sint cum.
                following: false
                image: In voluptatum tempore error occaecati quis.
                username: Dolorum rerum eum nisi voluptatem.
            required:
                - username
                - bio
                - image
                - following
        RegisterRequestBody:
            type: object
            properties:
                email:
                    type: string
                    example: jermaine.cruickshank@oharakoch.com
                    format: email
                password:
                    type: string
                    example: c56
                    minLength: 6
                    maxLength: 128
                username:
                    type: string
                    example: MJZZ
                    pattern: ^[a-zA-Z0-9_]{3,32}$
            example:
                email: torey@barton.info
                password: 5ef
                username: V6SoheX3
            required:
                - username
                - email
                - password
        UpdateRequestBody:
            type: object
            properties:
                bio:
                    type: string
                    example: f66
                    maxLength: 4096
                email:
                    type: string
                    example: kimberly@heaney.biz
                    format: email
                image:
                    type: string
                    example: https://i
                    pattern: ^https?://.+$
                password:
                    type: string
                    example: 6eh
                    minLength: 6
                    maxLength: 128
                username:
                    type: string
                    example: c5T
                    pattern: ^[a-zA-Z0-9_]{3,32}$
            example:
                bio: i85
                email: afton@anderson.name
                image: http://l
                password: zcr
                username: BHR41
        User:
            type: object
            properties:
                bio:
                    type: string
                    example: Et sint ut soluta libero.
                email:
                    type: string
                    example: Consequatur corporis rem et animi quam.
                image:
                    type: string
                    example: Aut debitis quos ut odio et accusamus.
                token:
                    type: string
                    example: Dolorum nam et.
                username:
                    type: string
                    example: Alias possimus voluptates rerum voluptatem nam.
            example:
                bio: Quia omnis magnam velit distinctio soluta.
                email: Vitae delectus alias laboriosam et cumque rerum.
                image: Quia odit excepturi possimus molestiae laudantium.
                token: Non eum eum porro dignissimos.
                username: Culpa nobis temporibus voluptas.
            required:
                - email
                - token
                - username
                - bio
                - image
tags:
    - name: profile
      description: profile
    - name: user
      description: user
