swagger: "2.0"
info:
    title: readworld app example
    description: readworld app example
    version: 0.0.1
host: localhost:8080
basePath: api
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/user/current:
        get:
            tags:
                - user
            summary: getCurrent user
            operationId: user#getCurrent
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UserGetCurrentResponseBody'
                        required:
                            - user
            schemes:
                - http
    /api/user/login:
        post:
            tags:
                - user
            summary: login user
            operationId: user#login
            parameters:
                - name: LoginRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UserLoginRequestBody'
                    required:
                        - email
                        - password
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UserLoginResponseBody'
                        required:
                            - user
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/UserLoginPasswordIsIncorrectResponseBody'
            schemes:
                - http
    /api/user/register:
        post:
            tags:
                - user
            summary: register user
            operationId: user#register
            parameters:
                - name: RegisterRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UserRegisterRequestBody'
                    required:
                        - username
                        - email
                        - password
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UserRegisterResponseBody'
                        required:
                            - user
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/UserRegisterEmailAlreadyUsedResponseBody'
            schemes:
                - http
    /api/user/update:
        post:
            tags:
                - user
            summary: update user
            operationId: user#update
            parameters:
                - name: UpdateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UserUpdateRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UserUpdateResponseBody'
                        required:
                            - user
            schemes:
                - http
definitions:
    User:
        title: User
        type: object
        properties:
            bio:
                type: string
                example: Nesciunt aliquid et dolore praesentium.
            email:
                type: string
                example: Nemo esse sed sed ea laborum qui.
            image:
                type: string
                example: Vel facilis.
            token:
                type: string
                example: Vero voluptas molestiae eos quae voluptatem.
            username:
                type: string
                example: Dignissimos quod exercitationem quaerat animi dolorem aut.
        example:
            bio: Quo incidunt quia neque et.
            email: Aspernatur sed quasi quisquam ullam ut.
            image: Omnis magni iste explicabo.
            token: Minus culpa nam.
            username: Reiciendis sit autem officiis nisi.
        required:
            - email
            - token
            - username
            - bio
            - image
    UserGetCurrentResponseBody:
        title: UserGetCurrentResponseBody
        type: object
        properties:
            user:
                $ref: '#/definitions/User'
        example:
            user:
                bio: Necessitatibus aut et maiores officiis placeat.
                email: Aliquid corrupti quae reprehenderit voluptates consequatur.
                image: Molestiae incidunt.
                token: Sint sit.
                username: Sed officia.
        required:
            - user
    UserLoginEmailNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: login_EmailNotFound_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserLoginPasswordIsIncorrectResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: login_PasswordIsIncorrect_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserLoginRequestBody:
        title: UserLoginRequestBody
        type: object
        properties:
            email:
                type: string
                example: emilie.haag@collier.name
                format: email
            password:
                type: string
                example: 9r9
                minLength: 6
                maxLength: 128
        example:
            email: zena.nitzsche@jacobi.name
            password: "593"
        required:
            - email
            - password
    UserLoginResponseBody:
        title: UserLoginResponseBody
        type: object
        properties:
            user:
                $ref: '#/definitions/User'
        example:
            user:
                bio: Necessitatibus aut et maiores officiis placeat.
                email: Aliquid corrupti quae reprehenderit voluptates consequatur.
                image: Molestiae incidunt.
                token: Sint sit.
                username: Sed officia.
        required:
            - user
    UserRegisterEmailAlreadyUsedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: register_EmailAlreadyUsed_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserRegisterRequestBody:
        title: UserRegisterRequestBody
        type: object
        properties:
            email:
                type: string
                example: manley@oconnelllangosh.biz
                format: email
            password:
                type: string
                example: "726"
                minLength: 6
                maxLength: 128
            username:
                type: string
                example: N7C
                pattern: ^[a-zA-Z0-9_]{3,32}$
        example:
            email: dwight_carter@hegmannosinski.net
            password: 2fn
            username: FTa
        required:
            - username
            - email
            - password
    UserRegisterResponseBody:
        title: UserRegisterResponseBody
        type: object
        properties:
            user:
                $ref: '#/definitions/User'
        example:
            user:
                bio: Necessitatibus aut et maiores officiis placeat.
                email: Aliquid corrupti quae reprehenderit voluptates consequatur.
                image: Molestiae incidunt.
                token: Sint sit.
                username: Sed officia.
        required:
            - user
    UserRegisterUsernameAlreadyUsedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: register_UsernameAlreadyUsed_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserUpdateRequestBody:
        title: UserUpdateRequestBody
        type: object
        properties:
            bio:
                type: string
                example: krr
                maxLength: 4096
            email:
                type: string
                example: cedrick@skiles.name
                format: email
            image:
                type: string
                example: http://m
                pattern: ^https?://.+$
            password:
                type: string
                example: bds
                minLength: 6
                maxLength: 128
            username:
                type: string
                example: 0ZN
                pattern: ^[a-zA-Z0-9_]{3,32}$
        example:
            bio: 09a
            email: tre.nicolas@deckowfisher.name
            image: https://d
            password: spo
            username: _P3z
    UserUpdateResponseBody:
        title: UserUpdateResponseBody
        type: object
        properties:
            user:
                $ref: '#/definitions/User'
        example:
            user:
                bio: Necessitatibus aut et maiores officiis placeat.
                email: Aliquid corrupti quae reprehenderit voluptates consequatur.
                image: Molestiae incidunt.
                token: Sint sit.
                username: Sed officia.
        required:
            - user
