openapi: 3.0.3
info:
    title: readworld app example
    description: readworld app example
    version: 0.0.1
servers:
    - url: http://localhost:8080
paths:
    /api/users:
        post:
            tags:
                - user
            summary: register user
            operationId: user#register
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RegisterRequestBody'
                        example:
                            email: javon_bartell@wehner.net
                            password: Voluptatibus ut nostrum laboriosam aliquid cum.
                            username: Voluptas aut veniam sed ut et enim.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Et optio qui.
                                    email: sedrick@terryauer.net
                                    image: Temporibus dolorem illo dolores esse et.
                                    token: Laboriosam quae autem sed ipsa est ratione.
                                    username: Nihil pariatur a.
    /api/users/login:
        post:
            tags:
                - user
            summary: login user
            operationId: user#login
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginRequestBody'
                        example:
                            email: shemar.barton@barton.net
                            password: Enim ab commodi odio voluptate.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                user:
                                    bio: Et optio qui.
                                    email: sedrick@terryauer.net
                                    image: Temporibus dolorem illo dolores esse et.
                                    token: Laboriosam quae autem sed ipsa est ratione.
                                    username: Nihil pariatur a.
components:
    schemas:
        LoginRequestBody:
            type: object
            properties:
                email:
                    type: string
                    example: erna_mcdermott@starkschultz.biz
                    format: email
                password:
                    type: string
                    example: Eligendi expedita.
            example:
                email: jennyfer@west.net
                password: Error occaecati quis earum.
            required:
                - email
                - password
        LoginResponseBody:
            type: object
            properties:
                user:
                    $ref: '#/components/schemas/UserType'
            example:
                user:
                    bio: Et optio qui.
                    email: sedrick@terryauer.net
                    image: Temporibus dolorem illo dolores esse et.
                    token: Laboriosam quae autem sed ipsa est ratione.
                    username: Nihil pariatur a.
            required:
                - user
        RegisterRequestBody:
            type: object
            properties:
                email:
                    type: string
                    example: clotilde@haley.biz
                    format: email
                password:
                    type: string
                    example: Veniam voluptatem quis.
                username:
                    type: string
                    example: Consequatur corporis rem et animi quam.
            example:
                email: tabitha_rogahn@blanda.net
                password: Qui temporibus minus enim.
                username: Quas quis.
            required:
                - username
                - email
                - password
        UserType:
            type: object
            properties:
                bio:
                    type: string
                    example: Quo voluptatibus et voluptatem asperiores praesentium vel.
                email:
                    type: string
                    example: candice@kesslerspinka.com
                    format: email
                image:
                    type: string
                    example: Necessitatibus ab.
                token:
                    type: string
                    example: Ea rem sequi deleniti suscipit enim.
                username:
                    type: string
                    example: Iste quibusdam maiores.
            example:
                bio: Aliquid voluptatem adipisci magnam placeat.
                email: yolanda@kling.net
                image: Itaque maiores atque ea.
                token: Non quis officiis.
                username: Quia illo porro itaque odit ex velit.
            required:
                - email
                - token
                - username
                - bio
                - image
tags:
    - name: user
      description: user
