swagger: "2.0"
info:
    title: readworld app example
    description: readworld app example
    version: 0.0.1
host: localhost:8080
basePath: api
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/users:
        post:
            tags:
                - user
            summary: register user
            operationId: user#register
            parameters:
                - name: RegisterRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UserRegisterRequestBody'
                    required:
                        - username
                        - email
                        - password
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UserRegisterResponseBody'
                        required:
                            - user
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/UserRegisterEmailAlreadyUsedResponseBody'
            schemes:
                - http
    /api/users/login:
        post:
            tags:
                - user
            summary: login user
            operationId: user#login
            parameters:
                - name: LoginRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/UserLoginRequestBody'
                    required:
                        - email
                        - password
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/UserLoginResponseBody'
                        required:
                            - user
            schemes:
                - http
definitions:
    UserLoginRequestBody:
        title: UserLoginRequestBody
        type: object
        properties:
            email:
                type: string
                example: elena@breitenbergbrekke.info
                format: email
            password:
                type: string
                example: Consequatur labore ea qui veniam voluptatibus.
        example:
            email: kathlyn@mckenzie.net
            password: Perferendis nesciunt aliquid et dolore praesentium dicta.
        required:
            - email
            - password
    UserLoginResponseBody:
        title: UserLoginResponseBody
        type: object
        properties:
            user:
                $ref: '#/definitions/UserType'
        example:
            user:
                bio: Sit aliquam rerum voluptatem rerum.
                email: Expedita non vel velit explicabo eveniet repudiandae.
                image: Quos ea minima labore.
                token: Et quam eos dolorum incidunt quia.
                username: Doloribus provident.
        required:
            - user
    UserRegisterEmailAlreadyUsedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: register_EmailAlreadyUsed_response_body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserRegisterRequestBody:
        title: UserRegisterRequestBody
        type: object
        properties:
            email:
                type: string
                example: bethel_harvey@gulgowskirath.com
                format: email
            password:
                type: string
                example: bjb
                minLength: 6
                maxLength: 128
            username:
                type: string
                example: 0{3, 32}
                pattern: ^[a-z0-9_]{3, 32}$
        example:
            email: murray.jaskolski@hoeger.com
            password: 2n5
            username: u{3, 32}
        required:
            - username
            - email
            - password
    UserRegisterResponseBody:
        title: UserRegisterResponseBody
        type: object
        properties:
            user:
                $ref: '#/definitions/UserType'
        example:
            user:
                bio: Sit aliquam rerum voluptatem rerum.
                email: Expedita non vel velit explicabo eveniet repudiandae.
                image: Quos ea minima labore.
                token: Et quam eos dolorum incidunt quia.
                username: Doloribus provident.
        required:
            - user
    UserRegisterUsernameAlreadyUsedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: register_UsernameAlreadyUsed_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    UserType:
        title: UserType
        type: object
        properties:
            bio:
                type: string
                example: Nam itaque fugiat sit quis.
            email:
                type: string
                example: Ipsum quaerat quia.
            image:
                type: string
                example: Reprehenderit fugit eum voluptas voluptas et laboriosam.
            token:
                type: string
                example: Et fugiat atque nostrum adipisci enim.
            username:
                type: string
                example: Aut doloremque.
        example:
            bio: Qui modi temporibus dolorem.
            email: Autem sed ipsa est.
            image: Dolores esse et non voluptas aut.
            token: Non nihil.
            username: A harum et.
        required:
            - email
            - token
            - username
            - bio
            - image
