// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: article.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteArticleContent = `-- name: DeleteArticleContent :exec
DELETE FROM article_content_ 
WHERE article_id_ = $1
`

func (q *Queries) DeleteArticleContent(ctx context.Context, db DBTX, articleID uuid.UUID) error {
	_, err := db.Exec(ctx, deleteArticleContent, articleID)
	return err
}

const deleteArticleFavorite = `-- name: DeleteArticleFavorite :exec
DELETE FROM article_favorite_
WHERE article_id_ = $1 AND user_id_ = $2
`

type DeleteArticleFavoriteParams struct {
	ArticleID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) DeleteArticleFavorite(ctx context.Context, db DBTX, arg DeleteArticleFavoriteParams) error {
	_, err := db.Exec(ctx, deleteArticleFavorite, arg.ArticleID, arg.UserID)
	return err
}

const getArticleContentByArticleID = `-- name: GetArticleContentByArticleID :one
SELECT 
  created_at_,
  updated_at_,
  article_id_,
  title_,
  description_,
  body_,
  author_user_id_
FROM article_content_ 
WHERE article_id_ = $1
LIMIT 1
`

func (q *Queries) GetArticleContentByArticleID(ctx context.Context, db DBTX, articleID uuid.UUID) (ArticleContent, error) {
	row := db.QueryRow(ctx, getArticleContentByArticleID, articleID)
	var i ArticleContent
	err := row.Scan(
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArticleID,
		&i.Title,
		&i.Description,
		&i.Body,
		&i.AuthorUserID,
	)
	return i, err
}

const getArticleStatsByArticleID = `-- name: GetArticleStatsByArticleID :one
SELECT 
  article_id_,
  favorites_count_
FROM article_stats_ 
WHERE article_id_ = $1
LIMIT 1
`

type GetArticleStatsByArticleIDRow struct {
	ArticleID      uuid.UUID
	FavoritesCount int64
}

func (q *Queries) GetArticleStatsByArticleID(ctx context.Context, db DBTX, articleID uuid.UUID) (GetArticleStatsByArticleIDRow, error) {
	row := db.QueryRow(ctx, getArticleStatsByArticleID, articleID)
	var i GetArticleStatsByArticleIDRow
	err := row.Scan(&i.ArticleID, &i.FavoritesCount)
	return i, err
}

const getArticleStatsByArticleIDForUpdate = `-- name: GetArticleStatsByArticleIDForUpdate :one
SELECT 
  article_id_,
  favorites_count_
FROM article_stats_ 
WHERE article_id_ = $1
LIMIT 1
FOR UPDATE
`

type GetArticleStatsByArticleIDForUpdateRow struct {
	ArticleID      uuid.UUID
	FavoritesCount int64
}

func (q *Queries) GetArticleStatsByArticleIDForUpdate(ctx context.Context, db DBTX, articleID uuid.UUID) (GetArticleStatsByArticleIDForUpdateRow, error) {
	row := db.QueryRow(ctx, getArticleStatsByArticleIDForUpdate, articleID)
	var i GetArticleStatsByArticleIDForUpdateRow
	err := row.Scan(&i.ArticleID, &i.FavoritesCount)
	return i, err
}

const insertArticle = `-- name: InsertArticle :exec
INSERT INTO article_
(created_at_, id_) 
VALUES ($1, $2)
`

type InsertArticleParams struct {
	CreatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) InsertArticle(ctx context.Context, db DBTX, arg InsertArticleParams) error {
	_, err := db.Exec(ctx, insertArticle, arg.CreatedAt, arg.ID)
	return err
}

const insertArticleComment = `-- name: InsertArticleComment :exec
INSERT INTO article_comment_
(created_at_, id_) 
VALUES ($1, $2)
`

type InsertArticleCommentParams struct {
	CreatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) InsertArticleComment(ctx context.Context, db DBTX, arg InsertArticleCommentParams) error {
	_, err := db.Exec(ctx, insertArticleComment, arg.CreatedAt, arg.ID)
	return err
}

const insertArticleCommentContent = `-- name: InsertArticleCommentContent :exec
INSERT INTO article_comment_content_
(created_at_, article_comment_id_, article_id_, body_, user_id_) 
VALUES ($1, $2, $3, $4, $5)
`

type InsertArticleCommentContentParams struct {
	CreatedAt        time.Time
	ArticleCommentID uuid.UUID
	ArticleID        uuid.UUID
	Body             string
	UserID           uuid.UUID
}

func (q *Queries) InsertArticleCommentContent(ctx context.Context, db DBTX, arg InsertArticleCommentContentParams) error {
	_, err := db.Exec(ctx, insertArticleCommentContent,
		arg.CreatedAt,
		arg.ArticleCommentID,
		arg.ArticleID,
		arg.Body,
		arg.UserID,
	)
	return err
}

const insertArticleCommentContentMutation = `-- name: InsertArticleCommentContentMutation :exec
INSERT INTO article_comment_content_mutation_
(created_at_, article_comment_id_, article_id_, body_, user_id_) 
VALUES ($1, $2, $3, $4, $5)
`

type InsertArticleCommentContentMutationParams struct {
	CreatedAt        time.Time
	ArticleCommentID uuid.UUID
	ArticleID        uuid.UUID
	Body             string
	UserID           uuid.UUID
}

func (q *Queries) InsertArticleCommentContentMutation(ctx context.Context, db DBTX, arg InsertArticleCommentContentMutationParams) error {
	_, err := db.Exec(ctx, insertArticleCommentContentMutation,
		arg.CreatedAt,
		arg.ArticleCommentID,
		arg.ArticleID,
		arg.Body,
		arg.UserID,
	)
	return err
}

const insertArticleContent = `-- name: InsertArticleContent :exec
INSERT INTO article_content_
(created_at_, updated_at_, article_id_, title_, description_, body_, author_user_id_) 
VALUES ($6, $6, $1, $2, $3, $4, $5)
`

type InsertArticleContentParams struct {
	ArticleID    uuid.UUID
	Title        string
	Description  string
	Body         string
	AuthorUserID uuid.UUID
	CreatedAt    time.Time
}

func (q *Queries) InsertArticleContent(ctx context.Context, db DBTX, arg InsertArticleContentParams) error {
	_, err := db.Exec(ctx, insertArticleContent,
		arg.ArticleID,
		arg.Title,
		arg.Description,
		arg.Body,
		arg.AuthorUserID,
		arg.CreatedAt,
	)
	return err
}

const insertArticleContentMutation = `-- name: InsertArticleContentMutation :exec
INSERT INTO article_content_mutation_
(created_at_, article_id_, title_, description_, body_, author_user_id_) 
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertArticleContentMutationParams struct {
	CreatedAt    time.Time
	ArticleID    uuid.UUID
	Title        string
	Description  string
	Body         string
	AuthorUserID uuid.UUID
}

func (q *Queries) InsertArticleContentMutation(ctx context.Context, db DBTX, arg InsertArticleContentMutationParams) error {
	_, err := db.Exec(ctx, insertArticleContentMutation,
		arg.CreatedAt,
		arg.ArticleID,
		arg.Title,
		arg.Description,
		arg.Body,
		arg.AuthorUserID,
	)
	return err
}

const insertArticleDeleted = `-- name: InsertArticleDeleted :exec
INSERT INTO article_deleted_
(created_at_, article_id_)
VALUES ($1, $2)
`

type InsertArticleDeletedParams struct {
	CreatedAt time.Time
	ArticleID uuid.UUID
}

func (q *Queries) InsertArticleDeleted(ctx context.Context, db DBTX, arg InsertArticleDeletedParams) error {
	_, err := db.Exec(ctx, insertArticleDeleted, arg.CreatedAt, arg.ArticleID)
	return err
}

const insertArticleFavorite = `-- name: InsertArticleFavorite :exec
INSERT INTO article_favorite_
(created_at_, article_id_, user_id_)
VALUES ($1, $2, $3)
`

type InsertArticleFavoriteParams struct {
	CreatedAt time.Time
	ArticleID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) InsertArticleFavorite(ctx context.Context, db DBTX, arg InsertArticleFavoriteParams) error {
	_, err := db.Exec(ctx, insertArticleFavorite, arg.CreatedAt, arg.ArticleID, arg.UserID)
	return err
}

const insertArticleFavoriteMutation = `-- name: InsertArticleFavoriteMutation :exec
INSERT INTO article_favorite_mutation_
(created_at_, article_id_, user_id_, type_)
VALUES ($1, $2, $3, $4)
`

type InsertArticleFavoriteMutationParams struct {
	CreatedAt time.Time
	ArticleID uuid.UUID
	UserID    uuid.UUID
	Type      ArticleFavoriteMutationType
}

func (q *Queries) InsertArticleFavoriteMutation(ctx context.Context, db DBTX, arg InsertArticleFavoriteMutationParams) error {
	_, err := db.Exec(ctx, insertArticleFavoriteMutation,
		arg.CreatedAt,
		arg.ArticleID,
		arg.UserID,
		arg.Type,
	)
	return err
}

const insertArticleStats = `-- name: InsertArticleStats :exec
INSERT INTO article_stats_
(created_at_, updated_at_, article_id_, favorites_count_)
VALUES ($3, $3, $1, $2)
`

type InsertArticleStatsParams struct {
	ArticleID      uuid.UUID
	FavoritesCount int64
	CreatedAt      time.Time
}

func (q *Queries) InsertArticleStats(ctx context.Context, db DBTX, arg InsertArticleStatsParams) error {
	_, err := db.Exec(ctx, insertArticleStats, arg.ArticleID, arg.FavoritesCount, arg.CreatedAt)
	return err
}

type InsertArticleTagParams struct {
	CreatedAt time.Time
	ArticleID uuid.UUID
	SeqNo     int32
	Tag       string
}

const insertArticleTagMutation = `-- name: InsertArticleTagMutation :exec
INSERT INTO article_tag_mutation_
(created_at_, article_id_, tags_) 
VALUES ($1, $2, $3)
`

type InsertArticleTagMutationParams struct {
	CreatedAt time.Time
	ArticleID uuid.UUID
	Tags      []byte
}

func (q *Queries) InsertArticleTagMutation(ctx context.Context, db DBTX, arg InsertArticleTagMutationParams) error {
	_, err := db.Exec(ctx, insertArticleTagMutation, arg.CreatedAt, arg.ArticleID, arg.Tags)
	return err
}

const isArticleFavoritedByArticleIDAndUserID = `-- name: IsArticleFavoritedByArticleIDAndUserID :one
SELECT EXISTS (
  SELECT 1
  FROM article_favorite_ 
  WHERE article_id_ = $1 AND user_id_ = $2
)
`

type IsArticleFavoritedByArticleIDAndUserIDParams struct {
	ArticleID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) IsArticleFavoritedByArticleIDAndUserID(ctx context.Context, db DBTX, arg IsArticleFavoritedByArticleIDAndUserIDParams) (bool, error) {
	row := db.QueryRow(ctx, isArticleFavoritedByArticleIDAndUserID, arg.ArticleID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listArticleContentsByArticleIDs = `-- name: ListArticleContentsByArticleIDs :many
SELECT 
  created_at_,
  updated_at_,
  article_id_,
  title_,
  description_,
  body_,
  author_user_id_
FROM article_content_ 
WHERE article_id_ = ANY($1::uuid[])
`

func (q *Queries) ListArticleContentsByArticleIDs(ctx context.Context, db DBTX, articleIds []uuid.UUID) ([]ArticleContent, error) {
	rows, err := db.Query(ctx, listArticleContentsByArticleIDs, articleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArticleContent
	for rows.Next() {
		var i ArticleContent
		if err := rows.Scan(
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArticleID,
			&i.Title,
			&i.Description,
			&i.Body,
			&i.AuthorUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticleIDsByFeed = `-- name: ListArticleIDsByFeed :many
SELECT ac.article_id_ 
FROM article_content_ ac
INNER JOIN user_follow_ follow 
  ON ac.author_user_id_ = follow.followed_user_id_
WHERE follow.user_id_ = $3
ORDER BY ac.updated_at_ DESC
LIMIT $1 OFFSET $2
`

type ListArticleIDsByFeedParams struct {
	Limit  int32
	Offset int32
	UserID uuid.UUID
}

func (q *Queries) ListArticleIDsByFeed(ctx context.Context, db DBTX, arg ListArticleIDsByFeedParams) ([]uuid.UUID, error) {
	rows, err := db.Query(ctx, listArticleIDsByFeed, arg.Limit, arg.Offset, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var article_id_ uuid.UUID
		if err := rows.Scan(&article_id_); err != nil {
			return nil, err
		}
		items = append(items, article_id_)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticleIDsBySearch = `-- name: ListArticleIDsBySearch :many
SELECT ac.article_id_ 
FROM article_content_ ac
INNER JOIN user_profile_ author 
  ON ac.author_user_id_ = author.user_id_ 
WHERE 
    CASE WHEN $3::text IS NULL THEN TRUE 
    ELSE EXISTS (SELECT 1 FROM article_tag_ WHERE article_id_ = ac.article_id_ AND tag_ = $3) END
  AND 
    CASE WHEN $4::text IS NULL THEN TRUE
    ELSE EXISTS (
      SELECT 1 FROM article_favorite_ af 
      INNER JOIN user_profile_ up ON af.user_id_ = up.user_id_ 
      WHERE af.article_id_ = ac.article_id_ AND up.username_ = $4
    ) END
  AND
    CASE WHEN $5::text IS NULL THEN TRUE 
    ELSE author.username_ = $5 END
ORDER BY ac.updated_at_ DESC
LIMIT $1 OFFSET $2
`

type ListArticleIDsBySearchParams struct {
	Limit             int32
	Offset            int32
	Tag               *string
	FavoritedUsername *string
	AutherUsername    *string
}

func (q *Queries) ListArticleIDsBySearch(ctx context.Context, db DBTX, arg ListArticleIDsBySearchParams) ([]uuid.UUID, error) {
	rows, err := db.Query(ctx, listArticleIDsBySearch,
		arg.Limit,
		arg.Offset,
		arg.Tag,
		arg.FavoritedUsername,
		arg.AutherUsername,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var article_id_ uuid.UUID
		if err := rows.Scan(&article_id_); err != nil {
			return nil, err
		}
		items = append(items, article_id_)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticleStatsByArticleIDs = `-- name: ListArticleStatsByArticleIDs :many
SELECT 
  article_id_,
  favorites_count_
FROM article_stats_ 
WHERE article_id_ = ANY($1::uuid[])
`

type ListArticleStatsByArticleIDsRow struct {
	ArticleID      uuid.UUID
	FavoritesCount int64
}

func (q *Queries) ListArticleStatsByArticleIDs(ctx context.Context, db DBTX, articleIds []uuid.UUID) ([]ListArticleStatsByArticleIDsRow, error) {
	rows, err := db.Query(ctx, listArticleStatsByArticleIDs, articleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArticleStatsByArticleIDsRow
	for rows.Next() {
		var i ListArticleStatsByArticleIDsRow
		if err := rows.Scan(&i.ArticleID, &i.FavoritesCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticleTagByArticleID = `-- name: ListArticleTagByArticleID :many
SELECT 
  tag_
FROM article_tag_
WHERE article_id_ = $1
ORDER BY seq_no_ ASC
`

func (q *Queries) ListArticleTagByArticleID(ctx context.Context, db DBTX, articleID uuid.UUID) ([]string, error) {
	rows, err := db.Query(ctx, listArticleTagByArticleID, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag_ string
		if err := rows.Scan(&tag_); err != nil {
			return nil, err
		}
		items = append(items, tag_)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticleTagsByArticleIDs = `-- name: ListArticleTagsByArticleIDs :many
SELECT 
  article_id_,
  tag_
FROM article_tag_
WHERE article_id_ = ANY($1::uuid[])
ORDER BY article_id_, seq_no_ ASC
`

type ListArticleTagsByArticleIDsRow struct {
	ArticleID uuid.UUID
	Tag       string
}

func (q *Queries) ListArticleTagsByArticleIDs(ctx context.Context, db DBTX, articleIds []uuid.UUID) ([]ListArticleTagsByArticleIDsRow, error) {
	rows, err := db.Query(ctx, listArticleTagsByArticleIDs, articleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArticleTagsByArticleIDsRow
	for rows.Next() {
		var i ListArticleTagsByArticleIDsRow
		if err := rows.Scan(&i.ArticleID, &i.Tag); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavoritedArticlesByUserIDAndArticleIDs = `-- name: ListFavoritedArticlesByUserIDAndArticleIDs :many
SELECT 
  article_id_
FROM article_favorite_
WHERE user_id_ = $1
  AND article_id_ = ANY($2::uuid[])
`

type ListFavoritedArticlesByUserIDAndArticleIDsParams struct {
	UserID     uuid.UUID
	ArticleIds []uuid.UUID
}

func (q *Queries) ListFavoritedArticlesByUserIDAndArticleIDs(ctx context.Context, db DBTX, arg ListFavoritedArticlesByUserIDAndArticleIDsParams) ([]uuid.UUID, error) {
	rows, err := db.Query(ctx, listFavoritedArticlesByUserIDAndArticleIDs, arg.UserID, arg.ArticleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var article_id_ uuid.UUID
		if err := rows.Scan(&article_id_); err != nil {
			return nil, err
		}
		items = append(items, article_id_)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateArticleContent = `-- name: UpdateArticleContent :exec
UPDATE article_content_ SET 
  updated_at_ = $2,
  title_ = $3,
  description_ = $4,
  body_ = $5
WHERE article_id_ = $1
`

type UpdateArticleContentParams struct {
	ArticleID   uuid.UUID
	UpdatedAt   time.Time
	Title       string
	Description string
	Body        string
}

func (q *Queries) UpdateArticleContent(ctx context.Context, db DBTX, arg UpdateArticleContentParams) error {
	_, err := db.Exec(ctx, updateArticleContent,
		arg.ArticleID,
		arg.UpdatedAt,
		arg.Title,
		arg.Description,
		arg.Body,
	)
	return err
}

const updateArticleStatsFavoritesCount = `-- name: UpdateArticleStatsFavoritesCount :exec
UPDATE article_stats_
SET favorites_count_ = $1
WHERE article_id_ = $2
`

type UpdateArticleStatsFavoritesCountParams struct {
	FavoritesCount int64
	ArticleID      uuid.UUID
}

func (q *Queries) UpdateArticleStatsFavoritesCount(ctx context.Context, db DBTX, arg UpdateArticleStatsFavoritesCountParams) error {
	_, err := db.Exec(ctx, updateArticleStatsFavoritesCount, arg.FavoritesCount, arg.ArticleID)
	return err
}
