// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteUserFollow = `-- name: DeleteUserFollow :execrows
DELETE FROM user_follow_
WHERE user_id_ = $1 AND followed_user_id_ = $2
`

type DeleteUserFollowParams struct {
	UserID         uuid.UUID
	FollowedUserID uuid.UUID
}

func (q *Queries) DeleteUserFollow(ctx context.Context, arg DeleteUserFollowParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserFollow, arg.UserID, arg.FollowedUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPasswordHashByUserID = `-- name: GetPasswordHashByUserID :one
SELECT password_hash_ FROM user_auth_password_ 
WHERE user_id_ = $1
LIMIT 1
`

func (q *Queries) GetPasswordHashByUserID(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getPasswordHashByUserID, userID)
	var password_hash_ string
	err := row.Scan(&password_hash_)
	return password_hash_, err
}

const getUserEmailByUserID = `-- name: GetUserEmailByUserID :one
SELECT email_ FROM user_email_ 
WHERE user_id_ = $1
LIMIT 1
`

func (q *Queries) GetUserEmailByUserID(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserEmailByUserID, userID)
	var email_ string
	err := row.Scan(&email_)
	return email_, err
}

const getUserIDByEmail = `-- name: GetUserIDByEmail :one
SELECT user_id_ FROM user_email_ 
WHERE email_ = $1
LIMIT 1
`

func (q *Queries) GetUserIDByEmail(ctx context.Context, email string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByEmail, email)
	var user_id_ uuid.UUID
	err := row.Scan(&user_id_)
	return user_id_, err
}

const getUserProfileByUserID = `-- name: GetUserProfileByUserID :one
SELECT 
  username_, 
  bio_, 
  image_url_ 
FROM user_profile_
WHERE user_id_ = $1
LIMIT 1
`

type GetUserProfileByUserIDRow struct {
	Username string
	Bio      string
	ImageUrl string
}

func (q *Queries) GetUserProfileByUserID(ctx context.Context, userID uuid.UUID) (GetUserProfileByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getUserProfileByUserID, userID)
	var i GetUserProfileByUserIDRow
	err := row.Scan(&i.Username, &i.Bio, &i.ImageUrl)
	return i, err
}

const getUserProfileByUsername = `-- name: GetUserProfileByUsername :one
SELECT 
  user_id_, 
  bio_, 
  image_url_ 
FROM user_profile_
WHERE username_ = $1
LIMIT 1
`

type GetUserProfileByUsernameRow struct {
	UserID   uuid.UUID
	Bio      string
	ImageUrl string
}

func (q *Queries) GetUserProfileByUsername(ctx context.Context, username string) (GetUserProfileByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserProfileByUsername, username)
	var i GetUserProfileByUsernameRow
	err := row.Scan(&i.UserID, &i.Bio, &i.ImageUrl)
	return i, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO user_
(created_at_, id_) 
VALUES ($1, $2)
`

type InsertUserParams struct {
	CreatedAt time.Time
	ID        uuid.UUID
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser, arg.CreatedAt, arg.ID)
	return err
}

const insertUserAuthPassword = `-- name: InsertUserAuthPassword :exec
INSERT INTO user_auth_password_
(created_at_, updated_at_, user_id_, password_hash_) 
VALUES ($3, $3, $1, $2)
`

type InsertUserAuthPasswordParams struct {
	UserID       uuid.UUID
	PasswordHash string
	CreatedAt    time.Time
}

func (q *Queries) InsertUserAuthPassword(ctx context.Context, arg InsertUserAuthPasswordParams) error {
	_, err := q.db.Exec(ctx, insertUserAuthPassword, arg.UserID, arg.PasswordHash, arg.CreatedAt)
	return err
}

const insertUserEmail = `-- name: InsertUserEmail :exec
INSERT INTO user_email_
(created_at_, updated_at_, user_id_, email_) 
VALUES ($3, $3, $1, $2)
`

type InsertUserEmailParams struct {
	UserID    uuid.UUID
	Email     string
	CreatedAt time.Time
}

func (q *Queries) InsertUserEmail(ctx context.Context, arg InsertUserEmailParams) error {
	_, err := q.db.Exec(ctx, insertUserEmail, arg.UserID, arg.Email, arg.CreatedAt)
	return err
}

const insertUserEmailMutation = `-- name: InsertUserEmailMutation :exec
INSERT INTO user_email_mutation_
(created_at_, user_id_, email_) 
VALUES ($1, $2, $3)
`

type InsertUserEmailMutationParams struct {
	CreatedAt time.Time
	UserID    uuid.UUID
	Email     string
}

func (q *Queries) InsertUserEmailMutation(ctx context.Context, arg InsertUserEmailMutationParams) error {
	_, err := q.db.Exec(ctx, insertUserEmailMutation, arg.CreatedAt, arg.UserID, arg.Email)
	return err
}

const insertUserFollow = `-- name: InsertUserFollow :exec
INSERT INTO user_follow_
(created_at_, user_id_, followed_user_id_) 
VALUES ($1, $2, $3)
`

type InsertUserFollowParams struct {
	CreatedAt      time.Time
	UserID         uuid.UUID
	FollowedUserID uuid.UUID
}

func (q *Queries) InsertUserFollow(ctx context.Context, arg InsertUserFollowParams) error {
	_, err := q.db.Exec(ctx, insertUserFollow, arg.CreatedAt, arg.UserID, arg.FollowedUserID)
	return err
}

const insertUserFollowMutation = `-- name: InsertUserFollowMutation :exec
INSERT INTO user_follow_mutation_
(created_at_, user_id_, followed_user_id_, type_) 
VALUES ($1, $2, $3, $4)
`

type InsertUserFollowMutationParams struct {
	CreatedAt      time.Time
	UserID         uuid.UUID
	FollowedUserID uuid.UUID
	Type           UserFollowMutationType
}

func (q *Queries) InsertUserFollowMutation(ctx context.Context, arg InsertUserFollowMutationParams) error {
	_, err := q.db.Exec(ctx, insertUserFollowMutation,
		arg.CreatedAt,
		arg.UserID,
		arg.FollowedUserID,
		arg.Type,
	)
	return err
}

const insertUserProfile = `-- name: InsertUserProfile :exec
INSERT INTO user_profile_
(created_at_, updated_at_, user_id_, username_, bio_, image_url_) 
VALUES ($5, $5, $1, $2, $3, $4)
`

type InsertUserProfileParams struct {
	UserID    uuid.UUID
	Username  string
	Bio       string
	ImageUrl  string
	CreatedAt time.Time
}

func (q *Queries) InsertUserProfile(ctx context.Context, arg InsertUserProfileParams) error {
	_, err := q.db.Exec(ctx, insertUserProfile,
		arg.UserID,
		arg.Username,
		arg.Bio,
		arg.ImageUrl,
		arg.CreatedAt,
	)
	return err
}

const insertUserProfileMutation = `-- name: InsertUserProfileMutation :exec
INSERT INTO user_profile_mutation_
(created_at_, user_id_, username_, bio_, image_url_) 
VALUES ($1, $2, $3, $4, $5)
`

type InsertUserProfileMutationParams struct {
	CreatedAt time.Time
	UserID    uuid.UUID
	Username  string
	Bio       string
	ImageUrl  string
}

func (q *Queries) InsertUserProfileMutation(ctx context.Context, arg InsertUserProfileMutationParams) error {
	_, err := q.db.Exec(ctx, insertUserProfileMutation,
		arg.CreatedAt,
		arg.UserID,
		arg.Username,
		arg.Bio,
		arg.ImageUrl,
	)
	return err
}

const updateUserAuthPasswordHash = `-- name: UpdateUserAuthPasswordHash :exec
UPDATE user_auth_password_
SET updated_at_ = $2, password_hash_ = $3
WHERE user_id_ = $1
`

type UpdateUserAuthPasswordHashParams struct {
	UserID       uuid.UUID
	UpdatedAt    time.Time
	PasswordHash string
}

func (q *Queries) UpdateUserAuthPasswordHash(ctx context.Context, arg UpdateUserAuthPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserAuthPasswordHash, arg.UserID, arg.UpdatedAt, arg.PasswordHash)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE user_email_
SET updated_at_ = $2, email_ = $3
WHERE user_id_ = $1
`

type UpdateUserEmailParams struct {
	UserID    uuid.UUID
	UpdatedAt time.Time
	Email     string
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.UserID, arg.UpdatedAt, arg.Email)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE user_profile_
SET updated_at_ = $2, username_ = $3, bio_ = $4, image_url_ = $5 
WHERE user_id_ = $1
`

type UpdateUserProfileParams struct {
	UserID    uuid.UUID
	UpdatedAt time.Time
	Username  string
	Bio       string
	ImageUrl  string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.UserID,
		arg.UpdatedAt,
		arg.Username,
		arg.Bio,
		arg.ImageUrl,
	)
	return err
}
