// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_profile.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getUserProfile = `-- name: GetUserProfile :one
SELECT user_id_, username_ FROM user_profile_
WHERE user_id_ = $1
`

type GetUserProfileRow struct {
	UserID   uuid.UUID
	Username string
}

func (q *Queries) GetUserProfile(ctx context.Context, userID uuid.UUID) (GetUserProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getUserProfile, userID)
	var i GetUserProfileRow
	err := row.Scan(&i.UserID, &i.Username)
	return i, err
}
