name: Go

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'build target'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
      - name: before size
        run: df
      - name: Build
        run: |
          cd server
          go build -o /dev/null ${{ inputs.target }}
      - name: after size
        run: df
